apiVersion: apps/v1
kind: Deployment
metadata:
  name: produits
spec:
  replicas: 3
  selector:
    matchLabels:
      app: produits
  template:
    metadata:
      labels:
        app: produits
    spec:
      containers:
      - name: produits
        image: gcr.io/<project-id>/produits:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: produits
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: produits
