version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: produitsDb
      POSTGRES_USER: produitsUser
      POSTGRES_PASSWORD: produitsPwd
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    

volumes:
  postgres-data:

